### ISSUE TITLE
very good app

### ISSUE THREAD

**Issue by iksprteam** [belltown/Roku-TVGridExample#1]
aver my friend could you help me with this because this is what I was looking for would pay for their help want to run this script with another
@belltown

**Comment by iksprteam** [comment]
I want to do something like this

http://i.imgur.com/Nf76Bnp.png

**Comment by iksprteam** [comment]
if I could implement a guide to this app
[CustomPlaybackScreen.zip](https://github.com/belltown/Roku-TVGridExample/files/76136/CustomPlaybackScreen.zip)

@belltown

**Comment by iksprteam** [comment]
will pay for your help

**Comment by iksprteam** [comment]
can you do the job

**Comment by belltown** [comment]
No! And please stop sending me messages here and on the Roku forums.
